name: Publish

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Build and check package and app
        run: |
          pip install tox
          tox -e build,twinecheck

      # The gh-action-pypi-publish action runs in a container which is not
      # supported from a macos worker. To get around this, we store the wheel as
      # a temporary artifact, then download it in a follow-on job below.
      - name: Store the binary wheel
        uses: actions/upload-artifact@v2
        with:
          name: python-package-distributions
          path: dist

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download the binary wheel
        uses: actions/download-artifact@v2
        with:
          name: python-package-distributions
          path: dist/
      - name: Upload package
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
