# Copyright The Caikit Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Build and check package and app
        run: |
          pip install tox
          tox -e build,twinecheck

      # The gh-action-pypi-publish action runs in a container which is not
      # supported from a macos worker. To get around this, we store the wheel as
      # a temporary artifact, then download it in a follow-on job below.
      - name: Store the binary wheel
        uses: actions/upload-artifact@v2
        with:
          name: python-package-distributions
          path: dist

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download the binary wheel
        uses: actions/download-artifact@v2
        with:
          name: python-package-distributions
          path: dist/
      - name: Upload package
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
